### Register
POST http://localhost:3001/api/users/register
Content-Type: application/json

{
  "user": {
    "email": "johndoe@gmail.com",
    "password": "123456",
    "username": "john"
  }
}

### Login
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
  "user": {
    "email": "johndoe@gmail.com",
    "password": "123456"
  }
}